# Generated by Django 2.0.7 on 2018-07-05 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName_text', models.CharField(default=None, help_text='Please enter the name of the Customer', max_length=200, verbose_name='Name of the Customer')),
                ('FirmName_text', models.CharField(default=None, help_text='Please enter the name of the Firm', max_length=200, verbose_name='Name of the Firm')),
                ('description', models.TextField(blank=True, help_text='Write a brief description', max_length=100, verbose_name='Description of the Customer')),
                ('CustomerCellNumber', models.DecimalField(decimal_places=0, default=90, max_digits=12, validators=[django.core.validators.MaxValueValidator(999999999999)], verbose_name='Cell Phone Number')),
                ('CustomerWorkNumber', models.DecimalField(decimal_places=0, default=90, max_digits=12, validators=[django.core.validators.MaxValueValidator(999999999999)], verbose_name='Work Phone Number')),
                ('Subscription_date', models.DateTimeField(verbose_name='Start of the Subscription')),
                ('IsHeStillSub', models.BooleanField(default=False, verbose_name='Still Subscribed?')),
            ],
        ),
    ]
