# Generated by Django 2.0.7 on 2018-07-10 09:54

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaidName_text', models.CharField(default='', help_text='Please enter the name of the Paid Employee/Firm', max_length=200, verbose_name='Paid Person/Firm')),
                ('TypeOfDocument', models.CharField(choices=[('1', 'Fatura'), ('2', 'Fiş'), ('3', 'İrsaliye')], default='1', max_length=9)),
                ('DateOfDocument', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='The date of the Document')),
                ('DocumentID', models.CharField(default='', help_text='Please enter the document ID', max_length=200, verbose_name='Document ID')),
                ('PaymentStatus', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Payment Status')),
                ('PaymentDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of Payment')),
                ('PaymentSum', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MaxValueValidator(999999999999)], verbose_name='Payment Sum')),
                ('Currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EUR', 'EUR')], default='TL', max_length=9)),
                ('TotalSum', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Total Sum in TL')),
                ('description', models.TextField(blank=True, help_text='Write a brief description', max_length=100, verbose_name='Description of the Customer')),
                ('MethodOfPayment', models.CharField(help_text='Please enter the name of the Payer', max_length=200, verbose_name='Method Of Payment')),
                ('PayingEmployee', models.CharField(blank=True, help_text='Please enter the name of the Paying Employee', max_length=200, verbose_name='Name of the Paying Employee')),
                ('BooleanPayment', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'ordering': ['DateOfDocument'],
            },
        ),
        migrations.CreateModel(
            name='MainCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Main Categories',
            },
        ),
        migrations.CreateModel(
            name='SubCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('MainCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubCat', to='MoneyRelations.MainCat')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='MainCategory',
            field=models.ManyToManyField(to='MoneyRelations.MainCat'),
        ),
        migrations.AddField(
            model_name='expense',
            name='SubCategory',
            field=models.ManyToManyField(to='MoneyRelations.SubCat'),
        ),
    ]
