# Generated by Django 2.0.7 on 2018-07-13 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyRelations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='SubCategoryExpense',
            field=models.ForeignKey(default='', help_text='Please start typing.. Sub Category will appear after you select Main Category', max_length=30, on_delete=django.db.models.deletion.CASCADE, to='MoneyRelations.subcategory'),
        ),
    ]
