# Generated by Django 2.0.7 on 2018-07-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyRelations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='CustomerName_text',
            field=models.CharField(help_text='Please enter the name of the Customer', max_length=200, null=True, verbose_name='Name of the Customer'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='FirmName_text',
            field=models.CharField(help_text='Please enter the name of the Firm', max_length=200, null=True, verbose_name='Name of the Firm'),
        ),
    ]
