# Generated by Django 2.0.7 on 2018-07-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyRelations', '0003_auto_20180711_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcat',
            name='MainCategory',
        ),
        migrations.AlterField(
            model_name='expense',
            name='MainCategory',
            field=models.CharField(choices=[('1', 'Demirbaş'), ('2', 'Yatırım'), ('3', 'Sabit Gider'), ('4', 'Pazarlama')], default='', max_length=9, verbose_name='Main Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='PayingEmployee',
            field=models.CharField(help_text='Please enter the name of the Paying Employee', max_length=100, verbose_name='Name of the Paying Employee'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='SubCategory',
            field=models.CharField(choices=[('1', 'Ofis'), ('1', 'Bilgisayar'), ('1', 'Diğer'), ('2', 'Marka / Patent'), ('2', 'Diğer'), ('3', 'Ticket'), ('3', 'Ekip Yemek / Motivasyon'), ('3', 'IK'), ('3', 'Internet'), ('3', 'Aidat / Isınma'), ('3', 'Vergi/Harç/Noter'), ('3', 'Diğer'), ('4', 'POP'), ('4', 'Diğer')], default='', max_length=9, verbose_name='Sub Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, help_text='Write a brief description', max_length=100, verbose_name='Description of the Customer'),
        ),
        migrations.DeleteModel(
            name='MainCat',
        ),
        migrations.DeleteModel(
            name='SubCat',
        ),
    ]
