# Generated by Django 2.0.7 on 2018-07-05 09:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyRelations', '0003_auto_20180705_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='CustomerCellNumber',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='CustomerName_text',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='CustomerWorkNumber',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='FirmName_text',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='IsHeStillSub',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='Subscription_date',
        ),
        migrations.AddField(
            model_name='expense',
            name='DateOfDocument',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='The date of the Document'),
        ),
        migrations.AddField(
            model_name='expense',
            name='MainCategory',
            field=models.CharField(blank=True, help_text='Please enter the name of the Category', max_length=200, verbose_name='Payer Person/Firm'),
        ),
        migrations.AddField(
            model_name='expense',
            name='MethodOfPayment',
            field=models.CharField(blank=True, help_text='Please enter the name of the Payer', max_length=200, verbose_name='Payer Person/Firm'),
        ),
        migrations.AddField(
            model_name='expense',
            name='PayerName_text',
            field=models.CharField(blank=True, help_text='Please enter the name of the Payer', max_length=200, verbose_name='Payer Person/Firm'),
        ),
        migrations.AddField(
            model_name='expense',
            name='PayingEmployee',
            field=models.CharField(blank=True, help_text='Please enter the name of the Payer', max_length=200, verbose_name='Payer Person/Firm'),
        ),
        migrations.AddField(
            model_name='expense',
            name='PaymentDate',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Date of Payment'),
        ),
        migrations.AddField(
            model_name='expense',
            name='PaymentStatus',
            field=models.BooleanField(default=True, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='expense',
            name='PaymentSum',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MaxValueValidator(999999999999)], verbose_name='Cell Phone Number'),
        ),
        migrations.AddField(
            model_name='expense',
            name='SubCategory',
            field=models.CharField(blank=True, help_text='Please enter the name of the Payer', max_length=200, verbose_name='Payer Person/Firm'),
        ),
        migrations.AddField(
            model_name='expense',
            name='TypeOfDocument',
            field=models.CharField(blank=True, help_text='Please enter the type of the Document', max_length=200, verbose_name='Type of the Document'),
        ),
    ]
