# Generated by Django 2.0.7 on 2018-07-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyRelations', '0004_auto_20180711_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='TypeOfDocument',
            field=models.CharField(choices=[('Fature', 'Fatura'), ('Fiş', 'Fiş'), ('İrsaliye', 'İrsaliye')], default='1', max_length=9),
        ),
    ]
