# Generated by Django 2.0.7 on 2018-07-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyRelations', '0005_auto_20180711_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='TypeOfDocument',
            field=models.CharField(choices=[('Fatura', 'Fatura'), ('Fiş', 'Fiş'), ('İrsaliye', 'İrsaliye')], default='Fatura', max_length=9),
        ),
    ]
