# Generated by Django 2.0.7 on 2018-07-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyRelations', '0007_auto_20180711_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='PaymentStatus',
            field=models.CharField(choices=[('Paid', 'Yes'), ('Not Paid', 'No')], default='Yes', max_length=9),
        ),
    ]
