# Generated by Django 2.0.7 on 2018-07-11 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyRelations', '0008_auto_20180711_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='UltraTotalSum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MaxValueValidator(999999999999)], verbose_name='Payment Sum'),
        ),
    ]
