# Generated by Django 2.0.7 on 2018-07-12 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyRelations', '0009_expense_ultratotalsum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='PaymentDate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date of Payment'),
        ),
    ]
