# Generated by Django 2.0.7 on 2018-07-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyRelations', '0010_auto_20180712_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='MainCategory',
            field=models.CharField(default='', max_length=50, verbose_name='Main Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='SubCategory',
            field=models.CharField(default='', max_length=50, verbose_name='Sub Category'),
        ),
    ]
