# Generated by Django 2.0.7 on 2018-07-05 17:36

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20180705_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=django_countries.fields.CountryField(default='TR', max_length=2),
        ),
    ]
