# Generated by Django 2.0.7 on 2018-07-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20180705_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='shipped',
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment',
            field=models.BooleanField(default=True),
        ),
    ]
