# Generated by Django 2.0.7 on 2018-07-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_starting_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
